# Generated by Django 2.1.4 on 2018-12-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('Email_id', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('phone_no', models.IntegerField()),
                ('message', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='display',
            fields=[
                ('USERNAME', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ROOM_NO', models.IntegerField()),
                ('CHECK_IN_DATE', models.DateField()),
                ('CHECK_OUT_DATE', models.DateField()),
                ('TOTAL_COST', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=20)),
                ('available_rooms', models.IntegerField()),
                ('date', models.DateField()),
                ('card_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('rpassword', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='display',
            name='ROOM_TYPE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akbarhotel.RoomBooking'),
        ),
    ]
