# Generated by Django 2.1.4 on 2018-12-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akbarhotel', '0002_roombooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombooking',
            old_name='Check_in',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='Check_out',
        ),
    ]
