# Generated by Django 2.1.4 on 2018-12-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akbarhotel', '0004_roombooking_card_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='display',
            fields=[
                ('CHECK_IN_DATE', models.DateField()),
                ('CHECK_OUT_DATE', models.DateField()),
                ('USERNAME', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('CUSTOMER_ID', models.IntegerField()),
                ('TOTAL_COST', models.DecimalField(decimal_places=5, max_digits=10)),
                ('ROOM_TYPE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akbarhotel.RoomBooking')),
            ],
        ),
    ]
