# Generated by Django 2.1.4 on 2018-12-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akbarhotel', '0005_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='ROOM_NO',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
