# Generated by Django 2.1.4 on 2018-12-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akbarhotel', '0007_remove_display_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='CUSTOMER_ID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
