# Generated by Django 2.1.4 on 2018-12-15 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akbarhotel', '0009_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='CUSTOMER_ID',
        ),
    ]
